module.exports = [
    '[act] [natural]',
    '[action] [plan]',
    '[additional] [reduction]',
    '[adult] [children]',
    '[all] [alone]',
    '[almost] [exactly]',
    '[Alone] [together]',
    '[altogether] [separate]',
    '[another] [one]',
    '[anxious] [patient]',
    '[apparently] [invisible]',
    '[assistant] [principal]',
    '[assisted] [suicide]',
    '[athletic] [scholarship]',
    '[Audience] [viewing]',
    '[awfully] [good]',
    '[baby] [grand]',
    '[bad] [goods]',
    '[backdoor] [front]',	
    '[ball] [club]',
    '[ball] [diamond]',
    '[bar] [entrance]',
    '[barely] [dressed]',
    '[basic] [acid]',
    '[bed] [canopy]',
    '[behave] [badly]',
    '[benevolent] [despot]',
    '[benign] [neglect]',
    '[big] [baby]',
    '[black] [light]',
    '[blind] [spot]',
    '[Blue] [Blood]',
    '[boxing] [ring]',
    '[brief] [longing]',
    '[bring] [away]',
    '[building] [wrecking]',
    '[bus] [station]',
    '[calm] [breeze]',
    '[can’t] [can]',
    '[cardinal] [sin]',
    '[cheap] [jewelry]',
    '[cherry ] [tomato]',
    '[citizen] [ soldier]',
    '[civil ] [war]',
    '[class] [ clown]',
    '[classic ] [novel]',
    '[clean ] [dirt]',
    '[clearly] [ confused]',
    '[climb ] [down]',
    '[cold ] [sweat]',
    '[come ] [away]',
    '[conspicuous ] [absence]',
    '[constant ] [change]',
    '[constructive] [ criticism]',
    '[conventional] [ wisdom]',
    '[cost ] [savings]',
    '[crack] [ fix]',
    '[crash ] [landing]',
    '[crazy ] [sound]',
    '[criminal] [ justice]',
    '[critical] [ praise]',
    '[crowded ] [room]',
    '[cruel ] [joke]',
    '[cute ] [dog]',
    '[damaged ] [goods]',
    '[dark ] [spot]',
    '[deafening] [ silence]',
    '[death] [ benefits]',
    '[defensive ] [attack]',
    '[definite ] [possibility]',
    '[deliberate ] [mistake]',
    '[devilishly] [ good]',
    '[diamond ] [ring]',
    '[disaster ] [relief]',
    '[divorce] [ court]',
    '[doing ] [nothing]',
    '[don’t ] [do]',
    '[dotted ] [line]',
    '[double ] [solitaire]',
    '[down] [escalator]',
    '[drag] [ race]',
    '[dress ] [pants]',
    '[driving ] [stance]',
    '[dry] [martini]',
    '[dull] [roar]',
    '[easy] [task]',
    '[earth] [angel]',
    '[elevated] [subway]',
    '[emotional] [reasoning]',
    '[empty] [lots]',
    '[escaped] [prisoner]',
    '[essentially] [useless]',
    '[even] [odds]',
    '[executive] [secretary]',
    '[extensive] [briefing]',
    '[extinct] [life]',
    '[fairly] [dark]',
    '[fairly] [nasty]',
    '[far] [closer]',
    '[farewell] [reception]'];
